### ISSUE TITLE
Neues Spiel / Spiel erstellen

### ISSUE THREAD

**Issue by luii** [10ITX3-CardsAgainstHumanity/cah-backend#1]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/blob/970dfb6464ee61a77aae87605b8fb02fb606f802/src/lib/CahServer.ts#L45

Ein Spiel hat keinen maximal Punktestand, es wird gespielt bis man keine Lust mehr hat
oder alle das Spiel verlassen. Wäre also überflüssig das zu implementieren - sondern nur das der Punktestand von jedem Spieler getracked wird.

**Comment by MaxRobinSchaefer** [comment]
d.h. **Open End** für jedes Spiel?

**Comment by MaxRobinSchaefer** [comment]
maxScore wurde aus dem Game entfernt! https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/commit/604e1e0378e17f8ca36fc906d9bf548b7d462d92
