### ISSUE TITLE
Spiel ID im Frontend generieren

### ISSUE THREAD

**Issue by luii** [10ITX3-CardsAgainstHumanity/cah-backend#2]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/blob/develop/src/lib/CahServer.ts#L45-L59

Siehe Titel.

**Comment by MaxRobinSchaefer** [comment]
Game ID muss nun als Parameter bei `game.create` übergeben werden. https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/commit/8f0717495d90ef67f220bc5fa3bf2efb7657c0a9
