### ISSUE TITLE
rename shadowed player parameter

### ISSUE THREAD

**Issue by luii** [10ITX3-CardsAgainstHumanity/cah-backend#3]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/blob/6b3eecb00ebb3d8504153cf99d61500ff5654d6b/src/lib/Game.ts#L44-L45

**Comment by MaxRobinSchaefer** [comment]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/commit/03ef16dc18369b508f90088bfafb198a57da6c45

**Comment by luii** [comment]
player parameter still shadows the player parameter on map

**Comment by MaxRobinSchaefer** [comment]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/commit/5b83038d71947039a87981ee0c0825a2dfc2ee5c
