### ISSUE TITLE
use partial type utility

### ISSUE THREAD

**Issue by luii** [10ITX3-CardsAgainstHumanity/cah-backend#4]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/blob/6b3eecb00ebb3d8504153cf99d61500ff5654d6b/src/lib/Game.ts#L45

to

```js
let players: Partial<Player>[] = this.players.map((player: Player) => { 
```

when using keys from a type or class use partial to set the other properties / keys optional

```js
interface Todo {
    title: string;
    description: string;
}

function updateTodo(todo: Todo, fieldsToUpdate: Partial<Todo>) { <--
    return { ...todo, ...fieldsToUpdate };
}

const todo1 = {
    title: 'organize desk',
    description: 'clear clutter',
};

const todo2 = updateTodo(todo1, {
    description: 'throw out trash',
});
```

See: https://www.typescriptlang.org/docs/handbook/utility-types.html#partialt

**Comment by MaxRobinSchaefer** [comment]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/commit/03ef16dc18369b508f90088bfafb198a57da6c45
