### ISSUE TITLE
wrap the player object into a player property in the message 

### ISSUE THREAD

**Issue by luii** [10ITX3-CardsAgainstHumanity/cah-backend#5]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/blob/6b3eecb00ebb3d8504153cf99d61500ff5654d6b/src/lib/Game.ts#L63-L66

https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/blob/6b3eecb00ebb3d8504153cf99d61500ff5654d6b/src/lib/Game.ts#L79-L82

https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/blob/6b3eecb00ebb3d8504153cf99d61500ff5654d6b/src/lib/Game.ts#L35-L38

**Comment by MaxRobinSchaefer** [comment]
https://github.com/10ITX3-CardsAgainstHumanity/cah-backend/commit/b1d8c07dd8149818a9d5a63d253e7a9963f7c853
